language: ruby
rvm:
  - '2.1.5'
sudo: required
services:
  - docker
before_install:
  - rm -f Gemfile.lock
script: 
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - bundle exec rspec spec/acceptance

env:
  - PUPPET_VERSION=4.3.2 BEAKER_set="ci"