language: ruby
rvm:
  - '2.1.5'
sudo: required
services:
  - docker
before_install:
  - rm -f Gemfile.lock
script: 
  - bundle exec rspec spec/acceptance

env:
  - PUPPET_VERSION="~>3.0" BEAKER_set="ci"